"""BYOK provider presets (public catalog).

Platform demo still only uses MiniMax + StepFun env keys.
BYOK ("My keys") can bind any preset below; keys stay in RAM only.
"""

from __future__ import annotations

from typing import Any


# Protocol:
# - openai: POST {baseUrl}/chat/completions  (baseUrl may already end with /v1)
# - anthropic: POST {baseUrl}/messages       (baseUrl should include /v1 or vendor path)
PROVIDER_PRESETS: list[dict[str, Any]] = [
    {
        "id": "minimax",
        "displayName": "MiniMax",
        "productLine": "M3",
        "group": "platform",
        "groupLabel": "平台同款",
        "kind": "anthropic",
        "defaultModel": "MiniMax-M3",
        "models": ["MiniMax-M3", "MiniMax-M2.5-highspeed", "MiniMax-M2.5"],
        "needsLlmKey": True,
        "needsTtsKey": True,
        "needsBaseUrl": False,
        "regions": ["cn", "global"],
        "defaultRegion": "cn",
        "defaultBaseUrl": "https://api.minimaxi.com/anthropic/v1",
        "keyHintLlm": "sk- / sk-cp-",
        "keyHintTts": "Speech API secret",
        "docsUrl": "https://platform.minimaxi.com/",
        "consoleUrl": "https://platform.minimaxi.com/",
        "platformDemo": True,
    },
    {
        "id": "stepfun",
        "displayName": "StepFun",
        "productLine": "3.7 Flash",
        "group": "platform",
        "groupLabel": "平台同款",
        "kind": "openai",
        "defaultModel": "step-3.7-flash",
        "models": ["step-3.7-flash", "step-3.5-flash", "step-3.5-flash-2603"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.stepfun.com/v1",
        "keyHintLlm": "Bearer key",
        "keyHintTts": None,
        "docsUrl": "https://platform.stepfun.com/",
        "consoleUrl": "https://platform.stepfun.com/",
        "platformDemo": True,
    },
    {
        "id": "deepseek",
        "displayName": "DeepSeek",
        "productLine": "V4 Flash",
        "group": "official",
        "groupLabel": "官方直连",
        "kind": "openai",
        "defaultModel": "deepseek-v4-flash",
        "models": ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-chat"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.deepseek.com",
        "keyHintLlm": "sk-...",
        "keyHintTts": None,
        "docsUrl": "https://api-docs.deepseek.com",
        "consoleUrl": "https://platform.deepseek.com",
        "platformDemo": False,
    },
    {
        "id": "openai",
        "displayName": "OpenAI",
        "productLine": "GPT",
        "group": "official",
        "groupLabel": "官方直连",
        "kind": "openai",
        "defaultModel": "gpt-4o-mini",
        "models": ["gpt-4o-mini", "gpt-4.1-mini", "gpt-4o", "gpt-4.1"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.openai.com/v1",
        "keyHintLlm": "sk-...",
        "keyHintTts": None,
        "docsUrl": "https://platform.openai.com/api-keys",
        "consoleUrl": "https://platform.openai.com",
        "platformDemo": False,
    },
    {
        "id": "gemini",
        "displayName": "Google Gemini",
        "productLine": "Flash",
        "group": "official",
        "groupLabel": "官方直连",
        "kind": "openai",
        "defaultModel": "gemini-2.5-flash",
        "models": ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-2.0-flash-lite"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://generativelanguage.googleapis.com/v1beta/openai",
        "keyHintLlm": "AIza...",
        "keyHintTts": None,
        "docsUrl": "https://ai.google.dev/gemini-api/docs/openai",
        "consoleUrl": "https://aistudio.google.com/apikey",
        "platformDemo": False,
    },
    {
        "id": "moonshot",
        "displayName": "Kimi",
        "productLine": "K2",
        "group": "china",
        "groupLabel": "国内官方",
        "kind": "openai",
        "defaultModel": "kimi-k2.5",
        "models": ["kimi-k2.5", "kimi-k2-turbo-preview", "kimi-k2-thinking"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.moonshot.cn/v1",
        "keyHintLlm": "sk-...",
        "keyHintTts": None,
        "docsUrl": "https://platform.moonshot.cn",
        "consoleUrl": "https://platform.moonshot.cn",
        "platformDemo": False,
    },
    {
        "id": "qwen",
        "displayName": "通义千问",
        "productLine": "Qwen",
        "group": "china",
        "groupLabel": "国内官方",
        "kind": "openai",
        "defaultModel": "qwen-plus",
        "models": ["qwen-turbo", "qwen-plus", "qwen-max", "qwen-long"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "keyHintLlm": "sk-...",
        "keyHintTts": None,
        "docsUrl": "https://help.aliyun.com/zh/model-studio",
        "consoleUrl": "https://dashscope.console.aliyun.com",
        "platformDemo": False,
    },
    {
        "id": "zhipu",
        "displayName": "智谱 GLM",
        "productLine": "GLM-4",
        "group": "china",
        "groupLabel": "国内官方",
        "kind": "openai",
        "defaultModel": "glm-4-flash",
        "models": ["glm-4-flash", "glm-4-air", "glm-4-plus", "glm-4"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://open.bigmodel.cn/api/paas/v4",
        "keyHintLlm": "...",
        "keyHintTts": None,
        "docsUrl": "https://open.bigmodel.cn",
        "consoleUrl": "https://open.bigmodel.cn",
        "platformDemo": False,
    },
    {
        "id": "openrouter",
        "displayName": "OpenRouter",
        "productLine": "Multi",
        "group": "aggregator",
        "groupLabel": "聚合",
        "kind": "openai",
        "defaultModel": "openai/gpt-4o-mini",
        "models": [
            "openai/gpt-4o-mini",
            "google/gemini-2.0-flash-001",
            "deepseek/deepseek-chat",
            "anthropic/claude-3.5-haiku",
            "moonshotai/kimi-k2-0905",
        ],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://openrouter.ai/api/v1",
        "keyHintLlm": "sk-or-...",
        "keyHintTts": None,
        "docsUrl": "https://openrouter.ai/docs/quickstart",
        "consoleUrl": "https://openrouter.ai/keys",
        "platformDemo": False,
    },
    {
        "id": "siliconflow",
        "displayName": "硅基流动",
        "productLine": "SiliconFlow",
        "group": "aggregator",
        "groupLabel": "聚合",
        "kind": "openai",
        "defaultModel": "deepseek-ai/DeepSeek-V3",
        "models": [
            "deepseek-ai/DeepSeek-V3",
            "Qwen/Qwen2.5-72B-Instruct",
            "moonshotai/Kimi-K2-Instruct",
        ],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": False,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.siliconflow.cn/v1",
        "keyHintLlm": "sk-...",
        "keyHintTts": None,
        "docsUrl": "https://docs.siliconflow.cn",
        "consoleUrl": "https://cloud.siliconflow.cn",
        "platformDemo": False,
    },
    {
        "id": "custom",
        "displayName": "自定义",
        "productLine": "OpenAI 兼容",
        "group": "custom",
        "groupLabel": "自定义",
        "kind": "openai",
        "defaultModel": "gpt-4o-mini",
        "models": ["gpt-4o-mini", "deepseek-chat", "step-3.7-flash"],
        "needsLlmKey": True,
        "needsTtsKey": False,
        "needsBaseUrl": True,
        "regions": [],
        "defaultRegion": None,
        "defaultBaseUrl": "https://api.openai.com/v1",
        "keyHintLlm": "Bearer key",
        "keyHintTts": None,
        "docsUrl": "https://platform.openai.com/docs/api-reference",
        "consoleUrl": None,
        "platformDemo": False,
    },
]


def preset_by_id(provider_id: str) -> dict[str, Any] | None:
    pid = (provider_id or "").strip().lower()
    for p in PROVIDER_PRESETS:
        if p["id"] == pid:
            return p
    return None


def known_provider_ids() -> set[str]:
    return {p["id"] for p in PROVIDER_PRESETS}
